name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

permissions: 
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # Clean old artifacts FIRST
      - name: Delete Previous Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
          failOnError: FALSE

      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Build Directory
        run: mkdir -p _site && echo "Hello" > _site/index.html

      - name: List Artifacts (Debug)
        run: |
          echo "Existing artifacts:"
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq '.artifacts[] | .name'

      # Upload artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './_site'  # Replace with your build folder

      # Deploy
      - name: Deploy
        uses: actions/deploy-pages@v4
