name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Clean old artifacts FIRST
      - name: Delete Previous Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages

      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Build Directory
        run: ls -la ./_site  # Check if files exist

      - name: List Artifacts (Debug)
        run: |
          echo "Existing artifacts:"
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq '.artifacts[] | .name'

      # Upload artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './_site'  # Replace with your build folder

      # Deploy
      - name: Deploy
        uses: actions/deploy-pages@v4
